### ISSUE TITLE
A question regarding the use

### ISSUE THREAD

**Issue by herrwusel** [mancuniancol/context.magnetic.library#1]
What is the usecase of this? Does this help me to fill my library with dummy files which are opened by magnetizer?
Let's say I dont have anything in my library. Where would I use this addon?

Btw your addons are great. I really enjoy them!

**Comment by mancuniancol** [comment]
This addon has two objectives for me. Learn about the library integration  and personal shortcut. Lately, I am using Yatp as torrent player, but it doesn't have index like Quasar or Torrenter. Then the dummies files create the index that I need to call my series easy. 
About your question. I don't think so that this addon is for Quasar or Torrenter users. If you don't use Yatp, I don't see any point to install it.
