### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by kingdingaling83** [mancuniancol/context.magnetic.library#2]
for some reason nothing happens when i click this on a tv show
i have the path set in quasar and when i add shows directly in quasar using quasars own 'add to library' it works but not with magetic library

**Comment by mancuniancol** [comment]
Magnetic is independent of Quasar. Then, if that works or not in Quasar doesn't matter for Magnetic. 

Unfortunately, you are providing no information like logs and detail procedure your claim.  Then, it is impossible for me to help you

**Comment by kingdingaling83** [comment]
can i ask if this addon will check if you have existing episodes?

say i have season 1 on a hard drive but want 2,3 added using this?

**Comment by mancuniancol** [comment]
No, this context menu doesn't run as service and it only creates the shortcut to the library of the specific label that you are selecting. It doesn't creates season and episodes. 

In other words, it doesn't work like Quasar.  Sorry.

It is more to be used with Torrenter V2 or YAPT which don't have library integration. 

I will close this issue, because your request is not supported.

**Comment by kingdingaling83** [comment]
ok thanks for your info
